# Generated by Django 4.2.21 on 2025-05-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_reference_count_filereference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='storage_saved',
            field=models.BigIntegerField(default=0),
        ),
    ]
