# Generated by Django 4.2.21 on 2025-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_storage_saved'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_content_filename',
        ),
        migrations.RemoveConstraint(
            model_name='filereference',
            name='unique_reference_name',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_filename',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='reference_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['original_filename', 'file_type'], name='files_file_origina_4afc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['size', 'uploaded_at'], name='files_file_size_4a9580_idx'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash__isnull', False)), fields=('content_hash',), name='unique_content'),
        ),
    ]
