# Generated by Django 4.2.21 on 2025-05-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_remove_file_unique_content_alter_file_content_hash_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash__isnull', False)), fields=('content_hash',), name='unique_content_hash'),
        ),
    ]
