# Generated by Django 4.2.21 on 2025-05-23 05:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_content_hash_file_unique_content_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='reference_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FileReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='files.file')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='filereference',
            constraint=models.UniqueConstraint(fields=('reference_name',), name='unique_reference_name'),
        ),
    ]
