# Generated by Django 4.2.21 on 2025-05-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_remove_file_unique_content_filename_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_content',
        ),
        migrations.AlterField(
            model_name='file',
            name='content_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['content_hash', 'size'], name='files_file_content_8cb838_idx'),
        ),
    ]
